name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
        build_type: [Debug, Release]
        sanitizers: ["address,undefined", ""]
        exclude:
          - build_type: Release
            sanitizers: "address,undefined"

    steps:
      - name: clone
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-unknown-elf build-essential cmake python3 gcc-14 llvm clang libclang-dev

      - name: build
        run: |
          cmake -S . -B build \
            -DUSE_SANITIZER='${{matrix.sanitizers}}' \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
          cmake --build build --parallel `nproc`

      - name: test
        run: |
          ctest --test-dir build --output-on-failure

